server:
  port: 8777
spring:
  application:
    name: service-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
zuul:
  routes:
    apia:
      path: /apia/**
      serviceId: ribbon-service-hi
    apib:
      path: /apib/**
      serviceId: service-feign